name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t prashant9711/astronomy_notifier:latest . 
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push Docker image to registry
        run: |
          docker push prashant9711/astronomy_notifier:latest

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PEM }}
          port: 22
          script: |
            sudo docker container ls
            sudo docker stop 8a6dad6580aa
            sudo docker rm 8a6dad6580aa
            echo "Connected to EC2 successfully!"
            # Pull the Docker image
            sudo docker pull prashant9711/astronomy_notifier:latest
            echo "Docker pull successful"
            # Run the Docker container
            sudo docker run -e NASA_API="${{ secrets.NASA_API }}" -d -p 5000:5000 prashant9711/astronomy_notifier:latest
            # Verify Docker container is running
            sudo docker ps
